# Note: this file needs to be manually created on the server

defaults: &defaults
  secret_token: <%= ('x' * 128) %>
  host: localhost:3000

development:
  <<: *defaults

test:
  <<: *defaults


# https://github.com/binarylogic/settingslogic
#
# Usage:
# >> Rails.env
# => "development"
#
# >> Env.cool
# => "#<Settingslogic::Settings ... >"
#
# >> Env.cool.saweet
# => "nested settings"
#
# >> Env.neat_setting
# => 800
#
# defaults: &defaults
#   cool:
#     saweet: nested settings
#   neat_setting: 24
#
# development:
#   <<: *defaults
#   neat_setting: 800
#
# test:
#   <<: *defaults
